version: '3'

services:
  app:
    container_name: listing-api
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      DB_URL: "jdbc:postgresql://postgres/postgres"
      DB_USER: "heycar"
      DB_PASSWORD: "heycar"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: heycar
      POSTGRES_PASSWORD: heycar
